name: Metrics

on:
  schedule: [{cron: "0 */12 * * *"}]  # updates every 12 hours
  workflow_dispatch:                  # manual run

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SomiyaRana
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
